$(document).ready(function(){
	$("#tourbutton").click(function(){
		$("#tourcontent").fadeToggle();
	});
	$("#closetour").click(function(){
		$("#tourcontent").fadeOut();
	});
});
$(document).ready(function(){
	$("#socialcuescontent").click(function(){
		$("#bigalbumimage").hide();
		$(".hiddenalbum").fadeIn();
		$(".albumtitle").toggle();
	});
	$("#closealbum").click(function(){
		$("#bigalbumimage").fadeIn();
		$(".hiddenalbum").hide();
		$(".albumtitle").toggle();
	});
});
